### ISSUE TITLE
'CvRTrees' does not name a type in OpenCV 3.0.0

### ISSUE THREAD

**Issue by jmlich** [qgeissmann/OpenCFU#17]
I was trying to compile OpenCFU with OpenCV 3.0.0, but it doesn't work.
src/processor/headers/Predictor.hpp:23:9: error: 'CvRTrees' does not name a type

More detailed build log is available at 
https://copr-be.cloud.fedoraproject.org/results/sergiomb/opencv/fedora-22-x86_64/opencfu-3.8.11-3.fc22/build.log.gz

It seems that decision trees algorithms was completely rewritten in OpenCV 3.0.0.

**Comment by qgeissmann** [comment]
thanks for pointing that out, I will have to have a look when I come back from vacation (~15days).

**Comment by vjancik** [comment]
Is there any progress on this issue?

**Comment by qgeissmann** [comment]
I am going to fix this by the end of next week

**Comment by vjancik** [comment]
Hi, is the fix still segfaulting? Thanks.

**Comment by vjancik** [comment]
Hi, is this bug resolved by any chance?

**Comment by qgeissmann** [comment]
Hey, sorry, have bee v busy before Xmas. Will try to have a look soon ;)

**Comment by pkajaba** [comment]
Hello, Do you have any progress on this?

**Comment by jmlich** [comment]
Hi, by the way, Pavel Kajaba, Viktor Jancik and me are interested for same reason. I am former employee of Red Hat and I was looking how to update opencv package in fedora.

**Comment by pkajaba** [comment]
Hi, ping? :)

**Comment by qgeissmann** [comment]
Thanks for reminding me.
So we now support opencv3. There may be some issues with `Gtk3` vs `Gtk2` from the fact OpenCV3 uses `Gtk3` symbol as part of `highgui`. 
Let me know.

**Comment by anou85** [comment]
Hi @qgeissmann ,

I'm getting the same issue with OpenCV version 3.4.1 and the latest OpenCFU. Any recommendations?

In file included from src/processor/headers/Processor.hpp:9:0,
                 from src/main.cpp:23:
src/processor/headers/Predictor.hpp:23:9: error: ‘CvRTrees’ does not name a type
         CvRTrees m_trees;
         ^
src/processor/headers/Predictor.hpp:24:9: error: ‘CvRTParams’ does not name a type
         CvRTParams m_rt_params;

Cheers

**Comment by rexlogic** [comment]
> 
> 
> Hi @qgeissmann ,
> 
> I'm getting the same issue with OpenCV version 3.4.1 and the latest OpenCFU. Any recommendations?
> 
> In file included from src/processor/headers/Processor.hpp:9:0,
> from src/main.cpp:23:
> src/processor/headers/Predictor.hpp:23:9: error: ‘CvRTrees’ does not name a type
> CvRTrees m_trees;
> ^
> src/processor/headers/Predictor.hpp:24:9: error: ‘CvRTParams’ does not name a type
> CvRTParams m_rt_params;
> 
> Cheers

The OpenCFU source code (filename 'opencfu-3.9.0.tar.gz') available on Sourceforge is only compatible with OpenCV 2.4, and was not migrated to OpenCV 3.

Use the OpenCFU source code available on this git, with OpenCV > 3. It compiles (with only a few warnings) even under the Ubuntu 1804 WSL with OpenCV 4.0.1 (only install Xming as X Server for Windows to run its GUI).

**Comment by qgeissmann** [comment]
Hi @rexlogic, 
Thanks, so if I understand well, the github source code compiles and we just need to update/redirect the code on sourceforge?

**Comment by rexlogic** [comment]
> 
> 
> Hi @rexlogic,
> Thanks, so if I understand well, the github source code compiles and we just need to update/redirect the code on sourceforge?

Hi @qgeissmann,

Yes, a linux archive with the new code on Sourceforge should create less confusion. And an attached note like "compile using _OpenCV 3+_" would be even better.
Also suggesting it is not a minor update, - migration to the new _OpenCV_ namespaces changes alot of code; less the GUI - and the _OpenCFU_ versioning can climb to 4.0.
