### ISSUE TITLE
Missing configure in github repo

### ISSUE THREAD

**Issue by nullglob** [qgeissmann/OpenCFU#19]
Hi,

It looks like the configure file is missing from the github repo. It's present in the sourceforge tar.gz bundle, however. Perhaps I am missing something...

Regards,
nullglob

**Comment by qgeissmann** [comment]
Hey there,

As a developer, you can generate the configure. Typically:

```
autoreconf -i
./configure 
make
make install
```

**Comment by nullglob** [comment]
Great - thanks for explaining that. I was missing the autoreconf step.

Perhaps you could add this step to the procedure described in INSTALL file
(which is where I looked first for install instructions).
