### ISSUE TITLE
Docker Compatibility achieved

### ISSUE THREAD

**Issue by mapo121** [qgeissmann/OpenCFU#35]
I got Docker (a virtualized environment) that will enable openCFU to run on MacOS and Windows. It's running a container of Fedora.

If anyone is interested, feel free to reach out to mapo3126@gmail.com. I'm still testing it, but this software is very useful for research.

I'm not sure if @qgeissmann monitors this issue page, but I'd like to know how I can contribute.

Thank you.

**Comment by tuttelikz** [comment]
@mapo121 interested :)
